# Generated by Django 4.1 on 2024-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
    ]
